
#!/usr/bin/env python3
from EntDetect._logging import setup_logger

"""
Slice frames from a Combined_GE pickle file generated by the G order parameter analysis.

The input pickle file contains a dict with a 'ref' key (reference frame data) and
integer frame-number keys mapping to per-frame entanglement data. This script extracts
a contiguous range of frames and writes a new pickle file containing only those frames
plus the 'ref' entry.

Usage example:
    python scripts/job_utilities/sliceCombined_GE_pklFiles.py \\
        --input  /scratch/ims86/EntDetect_Datastore/outputs/workflow2/GE/420_Combined_GE.pkl \\
        --output /scratch/ims86/EntDetect_Datastore/outputs/workflow2/GE/420_Combined_GE_last67.pkl \\
        --start  6600 \\
        --end    6666

Arguments:
    --input     Path to source Combined_GE pickle file                      [required]
    --output    Destination path for the sliced pickle file                 [required]
    --start     First frame index to keep, inclusive (default: 0)
    --end       Last frame index to keep, inclusive (default: keep all)
    --log_level Logging verbosity: DEBUG, INFO, WARNING, ERROR (default: INFO)
    --logdir    Directory for log file (default: same directory as --output)
"""


##########################################################################################################################################################
def load_pickle(filename, start_frame, end_frame, logger):
    """Load a Combined_GE pickle file and filter to the requested frame range.

    The 'ref' key is always retained regardless of the frame range.

    Parameters
    ----------
    filename : str
        Path to the source pickle file.
    start_frame : int or None
        Minimum frame index to keep (inclusive).
    end_frame : int or None
        Maximum frame index to keep (inclusive).
    logger : logging.Logger

    Returns
    -------
    dict
        Dict with 'ref' key and integer frame keys within [start_frame, end_frame].
    """
    import gc
    import pickle

    data_dict = {}
    logger.info(f'Loading pickle file: {filename}')
    with open(filename, 'rb') as fr:
        try:
            while True:
                chunk = pickle.load(fr)
                logger.debug(f'Loaded chunk with {len(chunk)} keys')

                if start_frame is not None or end_frame is not None:
                    logger.debug(f'Filtering chunk for frames [{start_frame}, {end_frame}]')
                    filtered_chunk = {}
                    for k, v in chunk.items():
                        if k == 'ref':
                            filtered_chunk[k] = v
                        elif ((start_frame is None or k >= start_frame) and
                              (end_frame   is None or k <= end_frame)):
                            filtered_chunk[k] = v
                    del chunk  # CRITICAL: free large unfiltered dict before update
                    chunk = filtered_chunk

                logger.debug(f'Filtered chunk has {len(chunk)} keys')
                data_dict.update(chunk)
                del chunk

        except EOFError:
            pass

    n_frames = len(data_dict) - (1 if 'ref' in data_dict else 0)
    logger.info(f'Frames retained: {n_frames}')
    gc.collect()
    return data_dict
##########################################################################################################################################################


##########################################################################################################################################################
def save_pickle(filename, data, logger, protocol=4):
    """Write *data* to *filename* as a single pickle object."""
    import pickle
    logger.info(f'Saving sliced pickle to: {filename}')
    with open(filename, 'wb') as fh:
        pickle.dump(data, fh, protocol=protocol)
    logger.info(f'SAVED: {filename}')
##########################################################################################################################################################


##########################################################################################################################################################
def main(argv=None):

    ###---------------------------------------------------------------------------------------------------------
    import sys
    import os
    import argparse
    import time

    start_time = time.time()
    ###---------------------------------------------------------------------------------------------------------

    ###---------------------------------------------------------------------------------------------------------
    parser = argparse.ArgumentParser(
        description="Slice frames from a Combined_GE pickle file.")
    parser.add_argument("--input",  type=str, required=True,
                        help="Path to source Combined_GE pickle file")
    parser.add_argument("--output", type=str, required=True,
                        help="Destination path for the sliced pickle file")
    parser.add_argument("--start",  type=int, default=None,
                        help="First frame index to keep, inclusive (default: keep from beginning)")
    parser.add_argument("--end",    type=int, default=None,
                        help="Last frame index to keep, inclusive (default: keep to end)")
    parser.add_argument("--log_level", default="INFO",
                        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
                        help="Logging verbosity (default: INFO)")
    parser.add_argument("--logdir", type=str, default=None,
                        help="Directory for log file (default: same directory as --output)")
    args = parser.parse_args(argv)
    ###---------------------------------------------------------------------------------------------------------

    ###---------------------------------------------------------------------------------------------------------
    import logging
    log_level = getattr(logging, args.log_level.upper(), logging.INFO)

    outdir  = os.path.dirname(os.path.abspath(args.output))
    logdir  = args.logdir if args.logdir is not None else outdir
    ID      = os.path.splitext(os.path.basename(args.output))[0]
    os.makedirs(outdir, exist_ok=True)

    logger = setup_logger('sliceCombined_GE_pklFiles', outdir=logdir, ID=ID, log_level=log_level)
    logger.info(f'args: {args}')
    ###---------------------------------------------------------------------------------------------------------

    ###---------------------------------------------------------------------------------------------------------
    # Input validation
    if not os.path.exists(args.input):
        logger.error(f'ERROR: Input file not found: {args.input}')
        sys.exit(1)

    if args.start is not None and args.end is not None and args.start > args.end:
        logger.error(f'ERROR: --start ({args.start}) must be <= --end ({args.end})')
        sys.exit(1)
    ###---------------------------------------------------------------------------------------------------------

    ###---------------------------------------------------------------------------------------------------------
    data = load_pickle(args.input, args.start, args.end, logger)
    save_pickle(args.output, data, logger)
    ###---------------------------------------------------------------------------------------------------------

    logger.info(f'NORMAL TERMINATION - {time.time() - start_time:.1f} seconds')
    return 0
##########################################################################################################################################################


if __name__ == "__main__":
    raise SystemExit(main())
